#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2011-2024 Filipe Coelho <falktx@falktx.com>
# SPDX-License-Identifier: GPL-2.0-or-later

# ------------------------------------------------------------------------------------------------------------
# Imports (Global)

from qt_compat import qt_config

if qt_config == 5:
    from PyQt5.QtCore import Qt
    from PyQt5.QtGui import QColor, QFont, QPen, QPixmap
elif qt_config == 6:
    from PyQt6.QtCore import Qt
    from PyQt6.QtGui import QColor, QFont, QPen, QPixmap

# ------------------------------------------------------------------------------------------------------------


class Theme(object):
    # enum PortType
    THEME_PORT_SQUARE = 0
    THEME_PORT_POLYGON = 1

    # enum List
    THEME_MODERN_DARK = 0
    THEME_MODERN_DARK_TINY = 1
    THEME_MODERN_LIGHT = 2
    THEME_CLASSIC_DARK = 3
    THEME_OOSTUDIO = 4
    THEME_BLENDER_DARK = 5
    THEME_MAX = 6

    # enum BackgroundType
    THEME_BG_SOLID = 0
    THEME_BG_GRADIENT = 1

    def __init__(self, idx):
        object.__init__(self)
        self.idx = idx

        theme_data = self._get_themes_data().get(
            idx, self._get_themes_data()[self.THEME_MODERN_DARK]
        )
        for key, value in theme_data.items():
            setattr(self, key, value)

    def _get_themes_data(self):
        # Data-driven theme registry
        return {
            self.THEME_MODERN_DARK: {
                "canvas_bg": QColor(0, 0, 0),
                "box_pen": QPen(QColor(76, 77, 78), 1, Qt.SolidLine),
                "box_pen_sel": QPen(QColor(206, 207, 208), 1, Qt.DashLine),
                "box_bg_1": QColor(32, 34, 35),
                "box_bg_2": QColor(43, 47, 48),
                "box_shadow": QColor(89, 89, 89, 180),
                "box_header_pixmap": None,
                "box_header_height": 24,
                "box_header_spacing": 0,
                "box_text": QPen(QColor(240, 240, 240), 0),
                "box_text_sel": QPen(QColor(240, 240, 240), 0),
                "box_text_ypos": 16,
                "box_font_name": "Deja Vu Sans",
                "box_font_size": 11,
                "box_font_state": QFont.Bold,
                "box_bg_type": self.THEME_BG_GRADIENT,
                "box_use_icon": True,
                "port_text": QPen(QColor(250, 250, 250), 0),
                "port_bg_pixmap": None,
                "port_font_name": "Deja Vu Sans",
                "port_font_size": 11,
                "port_font_state": QFont.Normal,
                "port_mode": self.THEME_PORT_POLYGON,
                "port_audio_jack_pen": QPen(QColor(63, 90, 126), 1),
                "port_audio_jack_pen_sel": QPen(QColor(93, 120, 156), 1),
                "port_midi_jack_pen": QPen(QColor(159, 44, 42), 1),
                "port_midi_jack_pen_sel": QPen(QColor(189, 74, 72), 1),
                "port_midi_alsa_pen": QPen(QColor(93, 141, 46), 1),
                "port_midi_alsa_pen_sel": QPen(QColor(123, 171, 76), 1),
                "port_parameter_pen": QPen(QColor(137, 76, 43), 1),
                "port_parameter_pen_sel": QPen(QColor(167, 106, 73), 1),
                "port_audio_jack_bg": QColor(35, 61, 99),
                "port_audio_jack_bg_sel": QColor(85, 111, 149),
                "port_midi_jack_bg": QColor(120, 15, 16),
                "port_midi_jack_bg_sel": QColor(170, 65, 66),
                "port_midi_alsa_bg": QColor(64, 112, 18),
                "port_midi_alsa_bg_sel": QColor(114, 162, 68),
                "port_parameter_bg": QColor(101, 47, 16),
                "port_parameter_bg_sel": QColor(151, 97, 66),
                "port_audio_jack_text": QPen(QColor(250, 250, 250), 0),
                "port_audio_jack_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_midi_jack_text": QPen(QColor(250, 250, 250), 0),
                "port_midi_jack_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_midi_alsa_text": QPen(QColor(250, 250, 250), 0),
                "port_midi_alsa_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_parameter_text": QPen(QColor(250, 250, 250), 0),
                "port_parameter_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_height": 16,
                "port_offset": 0,
                "port_spacing": 2,
                "port_spacingT": 2,
                "line_audio_jack": QColor(63, 90, 126),
                "line_audio_jack_sel": QColor(153, 180, 216),
                "line_audio_jack_glow": QColor(100, 100, 200),
                "line_midi_jack": QColor(159, 44, 42),
                "line_midi_jack_sel": QColor(249, 134, 132),
                "line_midi_jack_glow": QColor(200, 100, 100),
                "line_midi_alsa": QColor(93, 141, 46),
                "line_midi_alsa_sel": QColor(183, 231, 136),
                "line_midi_alsa_glow": QColor(100, 200, 100),
                "line_parameter": QColor(137, 76, 43),
                "line_parameter_sel": QColor(227, 166, 133),
                "line_parameter_glow": QColor(166, 133, 133),
                "rubberband_pen": QPen(QColor(206, 207, 208), 1, Qt.SolidLine),
                "rubberband_brush": QColor(76, 77, 78, 100),
            },
            self.THEME_MODERN_DARK_TINY: {
                "canvas_bg": QColor(0, 0, 0),
                "box_pen": QPen(QColor(76, 77, 78), 1, Qt.SolidLine),
                "box_pen_sel": QPen(QColor(206, 207, 208), 1, Qt.DashLine),
                "box_bg_1": QColor(32, 34, 35),
                "box_bg_2": QColor(43, 47, 48),
                "box_shadow": QColor(89, 89, 89, 180),
                "box_header_pixmap": None,
                "box_header_height": 14,
                "box_header_spacing": 0,
                "box_text": QPen(QColor(240, 240, 240), 0),
                "box_text_sel": QPen(QColor(240, 240, 240), 0),
                "box_text_ypos": 10,
                "box_font_name": "Deja Vu Sans",
                "box_font_size": 10,
                "box_font_state": QFont.Bold,
                "box_bg_type": self.THEME_BG_GRADIENT,
                "box_use_icon": False,
                "port_text": QPen(QColor(250, 250, 250), 0),
                "port_bg_pixmap": None,
                "port_font_name": "Deja Vu Sans",
                "port_font_size": 9,
                "port_font_state": QFont.Normal,
                "port_mode": self.THEME_PORT_POLYGON,
                "port_audio_jack_pen": QPen(QColor(63, 90, 126), 1),
                "port_audio_jack_pen_sel": QPen(QColor(93, 120, 156), 1),
                "port_midi_jack_pen": QPen(QColor(159, 44, 42), 1),
                "port_midi_jack_pen_sel": QPen(QColor(189, 74, 72), 1),
                "port_midi_alsa_pen": QPen(QColor(93, 141, 46), 1),
                "port_midi_alsa_pen_sel": QPen(QColor(123, 171, 76), 1),
                "port_parameter_pen": QPen(QColor(137, 76, 43), 1),
                "port_parameter_pen_sel": QPen(QColor(167, 106, 73), 1),
                "port_audio_jack_bg": QColor(35, 61, 99),
                "port_audio_jack_bg_sel": QColor(85, 111, 149),
                "port_midi_jack_bg": QColor(120, 15, 16),
                "port_midi_jack_bg_sel": QColor(170, 65, 66),
                "port_midi_alsa_bg": QColor(64, 112, 18),
                "port_midi_alsa_bg_sel": QColor(114, 162, 68),
                "port_parameter_bg": QColor(101, 47, 16),
                "port_parameter_bg_sel": QColor(151, 97, 66),
                "port_audio_jack_text": QPen(QColor(250, 250, 250), 0),
                "port_audio_jack_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_midi_jack_text": QPen(QColor(250, 250, 250), 0),
                "port_midi_jack_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_midi_alsa_text": QPen(QColor(250, 250, 250), 0),
                "port_midi_alsa_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_parameter_text": QPen(QColor(250, 250, 250), 0),
                "port_parameter_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_height": 12,
                "port_offset": 0,
                "port_spacing": 1,
                "port_spacingT": 1,
                "line_audio_jack": QColor(63, 90, 126),
                "line_audio_jack_sel": QColor(153, 180, 216),
                "line_audio_jack_glow": QColor(100, 100, 200),
                "line_midi_jack": QColor(159, 44, 42),
                "line_midi_jack_sel": QColor(249, 134, 132),
                "line_midi_jack_glow": QColor(200, 100, 100),
                "line_midi_alsa": QColor(93, 141, 46),
                "line_midi_alsa_sel": QColor(183, 231, 136),
                "line_midi_alsa_glow": QColor(100, 200, 100),
                "line_parameter": QColor(137, 76, 43),
                "line_parameter_sel": QColor(227, 166, 133),
                "line_parameter_glow": QColor(166, 133, 133),
                "rubberband_pen": QPen(QColor(206, 207, 208), 1, Qt.SolidLine),
                "rubberband_brush": QColor(76, 77, 78, 100),
            },
            self.THEME_MODERN_LIGHT: {
                "canvas_bg": QColor(248, 249, 250),
                "box_pen": QPen(QColor(176, 177, 178), 1, Qt.SolidLine),
                "box_pen_sel": QPen(QColor(1, 2, 3), 2, Qt.DashLine),
                "box_bg_1": QColor(250, 250, 250),
                "box_bg_2": QColor(200, 200, 200),
                "box_shadow": QColor(1, 1, 1, 100),
                "box_header_pixmap": None,
                "box_header_height": 24,
                "box_header_spacing": 0,
                "box_text": QPen(QColor(1, 1, 1), 0),
                "box_text_sel": QPen(QColor(1, 1, 1), 0),
                "box_text_ypos": 16,
                "box_font_name": "Ubuntu",
                "box_font_size": 11,
                "box_font_state": QFont.Bold,
                "box_bg_type": self.THEME_BG_GRADIENT,
                "box_use_icon": True,
                "port_text": QPen(QColor(255, 255, 255), 1),
                "port_bg_pixmap": None,
                "port_font_name": "Ubuntu",
                "port_font_size": 11,
                "port_font_state": QFont.Bold,
                "port_mode": self.THEME_PORT_POLYGON,
                "port_audio_jack_pen": QPen(QColor(103, 130, 166), 2),
                "port_audio_jack_pen_sel": QPen(QColor(239, 320, 356), 1),
                "port_midi_jack_pen": QPen(QColor(159, 44, 42), 1),
                "port_midi_jack_pen_sel": QPen(QColor(120, 74, 72), 1),
                "port_midi_alsa_pen": QPen(QColor(93, 141, 46), 1),
                "port_midi_alsa_pen_sel": QPen(QColor(123, 171, 76), 1),
                "port_parameter_pen": QPen(QColor(137, 76, 43), 1),
                "port_parameter_pen_sel": QPen(QColor(167, 106, 73), 1),
                "port_audio_jack_bg": QColor(0, 0, 180),
                "port_audio_jack_bg_sel": QColor(285, 311, 349),
                "port_midi_jack_bg": QColor(130, 15, 16),
                "port_midi_jack_bg_sel": QColor(120, 65, 66),
                "port_midi_alsa_bg": QColor(64, 112, 18),
                "port_midi_alsa_bg_sel": QColor(114, 162, 68),
                "port_parameter_bg": QColor(101, 47, 16),
                "port_parameter_bg_sel": QColor(151, 97, 66),
                "port_audio_jack_text": QPen(QColor(255, 255, 255), 1),
                "port_audio_jack_text_sel": QPen(QColor(255, 255, 255), 1),
                "port_midi_jack_text": QPen(QColor(255, 255, 255), 1),
                "port_midi_jack_text_sel": QPen(QColor(255, 255, 255), 1),
                "port_midi_alsa_text": QPen(QColor(255, 255, 255), 1),
                "port_midi_alsa_text_sel": QPen(QColor(255, 255, 255), 1),
                "port_parameter_text": QPen(QColor(255, 255, 255), 1),
                "port_parameter_text_sel": QPen(QColor(255, 255, 255), 1),
                "port_height": 16,
                "port_offset": 0,
                "port_spacing": 2,
                "port_spacingT": 2,
                "line_audio_jack": QColor(63, 90, 126),
                "line_audio_jack_sel": QColor(126, 180, 216),
                "line_audio_jack_glow": QColor(100, 100, 200),
                "line_midi_jack": QColor(159, 44, 42),
                "line_midi_jack_sel": QColor(203, 134, 132),
                "line_midi_jack_glow": QColor(200, 100, 100),
                "line_midi_alsa": QColor(93, 141, 46),
                "line_midi_alsa_sel": QColor(183, 231, 136),
                "line_midi_alsa_glow": QColor(100, 200, 100),
                "line_parameter": QColor(137, 43, 43),
                "line_parameter_sel": QColor(227, 166, 133),
                "line_parameter_glow": QColor(166, 133, 133),
                "rubberband_pen": QPen(QColor(206, 207, 208), 1, Qt.SolidLine),
                "rubberband_brush": QColor(76, 77, 78, 100),
            },
            self.THEME_CLASSIC_DARK: {
                "canvas_bg": QColor(0, 0, 0),
                "box_pen": QPen(QColor(77, 81, 73), 2, Qt.SolidLine),
                "box_pen_sel": QPen(QColor(147, 151, 143), 2, Qt.DashLine),
                "box_bg_1": QColor(30, 34, 36),
                "box_bg_2": QColor(30, 34, 36),
                "box_shadow": QColor(89, 89, 89, 180),
                "box_header_pixmap": None,
                "box_header_height": 19,
                "box_header_spacing": 0,
                "box_text": QPen(QColor(255, 255, 255), 0),
                "box_text_sel": QPen(QColor(255, 255, 255), 0),
                "box_text_ypos": 12,
                "box_font_name": "Sans",
                "box_font_size": 12,
                "box_font_state": QFont.Normal,
                "box_bg_type": self.THEME_BG_GRADIENT,
                "box_use_icon": False,
                "port_text": QPen(QColor(250, 250, 250), 0),
                "port_bg_pixmap": None,
                "port_font_name": "Sans",
                "port_font_size": 11,
                "port_font_state": QFont.Normal,
                "port_mode": self.THEME_PORT_SQUARE,
                "port_audio_jack_pen": QPen(QColor(35, 61, 99), 0, Qt.NoPen),
                "port_audio_jack_pen_sel": QPen(QColor(255, 0, 0), 0, Qt.NoPen),
                "port_midi_jack_pen": QPen(QColor(120, 15, 16), 0, Qt.NoPen),
                "port_midi_jack_pen_sel": QPen(QColor(255, 0, 0), 0, Qt.NoPen),
                "port_midi_alsa_pen": QPen(QColor(63, 112, 19), 0, Qt.NoPen),
                "port_midi_alsa_pen_sel": QPen(QColor(255, 0, 0), 0, Qt.NoPen),
                "port_parameter_pen": QPen(QColor(101, 47, 17), 0, Qt.NoPen),
                "port_parameter_pen_sel": QPen(QColor(255, 0, 0), 0, Qt.NoPen),
                "port_audio_jack_bg": QColor(35, 61, 99),
                "port_audio_jack_bg_sel": QColor(255, 0, 0),
                "port_midi_jack_bg": QColor(120, 15, 16),
                "port_midi_jack_bg_sel": QColor(255, 0, 0),
                "port_midi_alsa_bg": QColor(63, 112, 19),
                "port_midi_alsa_bg_sel": QColor(255, 0, 0),
                "port_parameter_bg": QColor(101, 47, 17),
                "port_parameter_bg_sel": QColor(255, 0, 0),
                "port_audio_jack_text": QPen(QColor(250, 250, 250), 0),
                "port_audio_jack_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_midi_jack_text": QPen(QColor(250, 250, 250), 0),
                "port_midi_jack_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_midi_alsa_text": QPen(QColor(250, 250, 250), 0),
                "port_midi_alsa_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_parameter_text": QPen(QColor(250, 250, 250), 0),
                "port_parameter_text_sel": QPen(QColor(250, 250, 250), 0),
                "port_height": 14,
                "port_offset": 0,
                "port_spacing": 1,
                "port_spacingT": 0,
                "line_audio_jack": QColor(53, 78, 116),
                "line_audio_jack_sel": QColor(255, 0, 0),
                "line_audio_jack_glow": QColor(255, 0, 0),
                "line_midi_jack": QColor(139, 32, 32),
                "line_midi_jack_sel": QColor(255, 0, 0),
                "line_midi_jack_glow": QColor(255, 0, 0),
                "line_midi_alsa": QColor(81, 130, 36),
                "line_midi_alsa_sel": QColor(255, 0, 0),
                "line_midi_alsa_glow": QColor(255, 0, 0),
                "line_parameter": QColor(120, 65, 33),
                "line_parameter_sel": QColor(255, 0, 0),
                "line_parameter_glow": QColor(255, 0, 0),
                "rubberband_pen": QPen(QColor(147, 151, 143), 2, Qt.SolidLine),
                "rubberband_brush": QColor(35, 61, 99, 100),
            },
            self.THEME_OOSTUDIO: {
                "canvas_bg": QColor(11, 11, 11),
                "box_pen": QPen(QColor(76, 77, 78), 1, Qt.SolidLine),
                "box_pen_sel": QPen(QColor(189, 122, 214), 1, Qt.DashLine),
                "box_bg_1": QColor(46, 46, 46),
                "box_bg_2": QColor(23, 23, 23),
                "box_shadow": QColor(89, 89, 89, 180),
                "box_header_pixmap": QPixmap(":/bitmaps/canvas/frame_node_header.png"),
                "box_header_height": 22,
                "box_header_spacing": 6,
                "box_text": QPen(QColor(144, 144, 144), 0),
                "box_text_sel": QPen(QColor(189, 122, 214), 0),
                "box_text_ypos": 16,
                "box_font_name": "Deja Vu Sans",
                "box_font_size": 11,
                "box_font_state": QFont.Bold,
                "box_bg_type": self.THEME_BG_SOLID,
                "box_use_icon": False,
                "port_text": QPen(QColor(155, 155, 155), 0),
                "port_bg_pixmap": QPixmap(":/bitmaps/canvas/frame_port_bg.png"),
                "port_font_name": "Deja Vu Sans",
                "port_font_size": 11,
                "port_font_state": QFont.Normal,
                "port_mode": self.THEME_PORT_SQUARE,
                "port_audio_jack_pen": QPen(QColor(23, 23, 23), 2),
                "port_audio_jack_pen_sel": QPen(QColor(1, 230, 238), 1),
                "port_midi_jack_pen": QPen(QColor(23, 23, 23), 2),
                "port_midi_jack_pen_sel": QPen(QColor(252, 118, 118), 1),
                "port_midi_alsa_pen": QPen(QColor(23, 23, 23), 2),
                "port_midi_alsa_pen_sel": QPen(QColor(129, 244, 118), 0),
                "port_parameter_pen": QPen(QColor(23, 23, 23), 2),
                "port_parameter_pen_sel": QPen(QColor(137, 76, 43), 1),
                "port_audio_jack_bg": QColor(46, 46, 46),
                "port_audio_jack_bg_sel": QColor(23, 23, 23),
                "port_midi_jack_bg": QColor(46, 46, 46),
                "port_midi_jack_bg_sel": QColor(23, 23, 23),
                "port_midi_alsa_bg": QColor(46, 46, 46),
                "port_midi_alsa_bg_sel": QColor(23, 23, 23),
                "port_parameter_bg": QColor(46, 46, 46),
                "port_parameter_bg_sel": QColor(23, 23, 23),
                "port_audio_jack_text": QPen(QColor(155, 155, 155), 0),
                "port_audio_jack_text_sel": QPen(QColor(1, 230, 238), 1),
                "port_midi_jack_text": QPen(QColor(155, 155, 155), 0),
                "port_midi_jack_text_sel": QPen(QColor(252, 118, 118), 1),
                "port_midi_alsa_text": QPen(QColor(155, 155, 155), 0),
                "port_midi_alsa_text_sel": QPen(QColor(129, 244, 118), 0),
                "port_parameter_text": QPen(QColor(155, 155, 155), 0),
                "port_parameter_text_sel": QPen(QColor(137, 76, 43), 1),
                "port_height": 21,
                "port_offset": 1,
                "port_spacing": 3,
                "port_spacingT": 0,
                "line_audio_jack": QColor(64, 64, 64),
                "line_audio_jack_sel": QColor(1, 230, 238),
                "line_audio_jack_glow": QColor(100, 200, 100),
                "line_midi_jack": QColor(64, 64, 64),
                "line_midi_jack_sel": QColor(252, 118, 118),
                "line_midi_jack_glow": QColor(200, 100, 100),
                "line_midi_alsa": QColor(64, 64, 64),
                "line_midi_alsa_sel": QColor(129, 244, 118),
                "line_midi_alsa_glow": QColor(100, 200, 100),
                "line_parameter": QColor(64, 64, 64),
                "line_parameter_sel": QColor(227, 166, 133),
                "line_parameter_glow": QColor(166, 133, 133),
                "rubberband_pen": QPen(QColor(1, 230, 238), 2, Qt.SolidLine),
                "rubberband_brush": QColor(90, 90, 90, 100),
            },
            self.THEME_BLENDER_DARK: {
                "canvas_bg": QColor(30, 30, 30),
                "box_pen": QPen(QColor(17, 17, 17), 1, Qt.SolidLine),
                "box_pen_sel": QPen(QColor(224, 149, 32), 1, Qt.SolidLine),
                "box_bg_1": QColor(66, 66, 66),
                "box_bg_2": QColor(45, 45, 45),
                "box_shadow": QColor(0, 0, 0, 150),
                "box_header_pixmap": None,
                "box_header_height": 22,
                "box_header_spacing": 0,
                "box_text": QPen(QColor(204, 204, 204), 0),
                "box_text_sel": QPen(QColor(255, 255, 255), 0),
                "box_text_ypos": 16,
                "box_font_name": "Deja Vu Sans",
                "box_font_size": 10,
                "box_font_state": QFont.Normal,
                "box_bg_type": self.THEME_BG_SOLID,
                "box_use_icon": False,
                "port_text": QPen(QColor(204, 204, 204), 0),
                "port_bg_pixmap": None,
                "port_font_name": "Deja Vu Sans",
                "port_font_size": 10,
                "port_font_state": QFont.Normal,
                "port_mode": self.THEME_PORT_POLYGON,
                "port_audio_jack_pen": QPen(QColor(25, 25, 25), 1),
                "port_audio_jack_pen_sel": QPen(QColor(224, 149, 32), 1),
                "port_midi_jack_pen": QPen(QColor(25, 25, 25), 1),
                "port_midi_jack_pen_sel": QPen(QColor(224, 149, 32), 1),
                "port_midi_alsa_pen": QPen(QColor(25, 25, 25), 1),
                "port_midi_alsa_pen_sel": QPen(QColor(224, 149, 32), 1),
                "port_parameter_pen": QPen(QColor(25, 25, 25), 1),
                "port_parameter_pen_sel": QPen(QColor(224, 149, 32), 1),
                "port_audio_jack_bg": QColor(84, 133, 161),
                "port_audio_jack_bg_sel": QColor(114, 163, 191),
                "port_midi_jack_bg": QColor(186, 74, 74),
                "port_midi_jack_bg_sel": QColor(216, 104, 104),
                "port_midi_alsa_bg": QColor(95, 163, 85),
                "port_midi_alsa_bg_sel": QColor(125, 193, 115),
                "port_parameter_bg": QColor(135, 113, 168),
                "port_parameter_bg_sel": QColor(165, 143, 198),
                "port_audio_jack_text": QPen(QColor(204, 204, 204), 0),
                "port_audio_jack_text_sel": QPen(QColor(255, 255, 255), 0),
                "port_midi_jack_text": QPen(QColor(204, 204, 204), 0),
                "port_midi_jack_text_sel": QPen(QColor(255, 255, 255), 0),
                "port_midi_alsa_text": QPen(QColor(204, 204, 204), 0),
                "port_midi_alsa_text_sel": QPen(QColor(255, 255, 255), 0),
                "port_parameter_text": QPen(QColor(204, 204, 204), 0),
                "port_parameter_text_sel": QPen(QColor(255, 255, 255), 0),
                "port_height": 14,
                "port_offset": 1,
                "port_spacing": 3,
                "port_spacingT": 1,
                "line_audio_jack": QColor(84, 133, 161),
                "line_audio_jack_sel": QColor(224, 149, 32),
                "line_audio_jack_glow": QColor(114, 163, 191),
                "line_midi_jack": QColor(186, 74, 74),
                "line_midi_jack_sel": QColor(224, 149, 32),
                "line_midi_jack_glow": QColor(216, 104, 104),
                "line_midi_alsa": QColor(95, 163, 85),
                "line_midi_alsa_sel": QColor(224, 149, 32),
                "line_midi_alsa_glow": QColor(125, 193, 115),
                "line_parameter": QColor(135, 113, 168),
                "line_parameter_sel": QColor(224, 149, 32),
                "line_parameter_glow": QColor(165, 143, 198),
                "rubberband_pen": QPen(QColor(224, 149, 32), 1, Qt.SolidLine),
                "rubberband_brush": QColor(255, 255, 255, 20),
            },
        }


# ------------------------------------------------------------------------------------------------------------


def getDefaultTheme():
    return Theme.THEME_MODERN_DARK


def getThemeName(idx):
    names = {
        Theme.THEME_MODERN_DARK: "Modern Dark",
        Theme.THEME_MODERN_DARK_TINY: "Modern Dark (Tiny)",
        Theme.THEME_MODERN_LIGHT: "Modern Light",
        Theme.THEME_CLASSIC_DARK: "Classic Dark",
        Theme.THEME_OOSTUDIO: "OpenOctave Studio",
        Theme.THEME_BLENDER_DARK: "Blender Dark",
    }
    return names.get(idx, "")


def getDefaultThemeName():
    return "Modern Dark"


# ------------------------------------------------------------------------------------------------------------
